In [30]:
#Uygulamada kullanılacak kütüphaneler tanımlanmıştır.
import os
import pandas as pd
import numpy as np

from sklearn.metrics import accuracy_score
from xgboost import XGBClassifier

from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import RandomForestClassifier

from sklearn.model_selection import train_test_split, GridSearchCV

from warnings import filterwarnings
filterwarnings('ignore')

from sklearn.metrics import confusion_matrix



In [31]:
df = pd.read_csv('labels.csv')

df = df.drop(labels=['Sample'], axis=1)
y = df['disease_type']

X = df.drop(labels=['disease_type'], axis=1)


print(X.head())

print(y)

   k__Viruses.f__Phycodnaviridae.g__Prasinovirus  \
0                                              0   
1                                              0   
2                                              2   
3                                              4   
4                                              2   

   k__Viruses.o__Caudovirales.f__Siphoviridae.g__Sfi1unalikevirus  \
0                                                  0                
1                                                  0                
2                                                  0                
3                                                  0                
4                                                  0                

   k__Viruses.o__Herpesvirales.f__Herpesviridae.g__Simplexvirus  \
0                                                 14              
1                                                 18              
2                                                484              
3   

In [32]:

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 50)


#Gradient Boosting Uygulaması
gb_model = GradientBoostingClassifier()
gb_model.fit(X_train, y_train)

y_pred=gb_model.predict(X_test)

In [33]:
table=confusion_matrix(y_test,y_pred)
print(table)

[[21  0  0  0]
 [ 0 28  0  0]
 [ 0  0  4  0]
 [ 0  0  0 18]]


In [34]:
from sklearn.metrics import precision_recall_fscore_support
res = []
for l in ["colon cancer","lung cancer","breast cancer","prosrtate cancer"]:
     prec,recall,_,_ = precision_recall_fscore_support(np.array(y_test)==l,
                                                  np.array(y_pred)==l,
                                                  pos_label=True,average=None)
     res.append([l,recall[0],recall[1]])

pd.DataFrame(res,columns = ['class','sensitivity','specificity'])

class  sensitivity  specificity
0      colon cancer          1.0          1.0
1       lung cancer          1.0          1.0
2     breast cancer          1.0          1.0
3  prosrtate cancer          1.0          1.0

In [35]:
#Random Forest Uygulaması
rf_model = RandomForestClassifier()
rf_model.fit(X_train, y_train)
y_pred=rf_model.predict(X_test)
table=confusion_matrix(y_test,y_pred)
print(table)

[[20  1  0  0]
 [ 0 27  0  1]
 [ 0  0  4  0]
 [ 0  0  0 18]]


In [36]:
res = []
for l in ["colon cancer","lung cancer","breast cancer","prosrtate cancer"]:
     prec,recall,_,_ = precision_recall_fscore_support(np.array(y_test)==l,
                                                  np.array(y_pred)==l,
                                                  pos_label=True,average=None)
     res.append([l,recall[0],recall[1]])

pd.DataFrame(res,columns = ['class','sensitivity','specificity'])

class  sensitivity  specificity
0      colon cancer     0.976744     0.964286
1       lung cancer     1.000000     1.000000
2     breast cancer     1.000000     0.952381
3  prosrtate cancer     0.981132     1.000000